<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'FGW' => 1,
        'DSJJ' => 2,
        'SCJGJ' => 3,
        'ZFW' => 4,
        'ZZB' => 5,
        'XCB' => 6,
        'GAJ' => 7,
        'JYJ' => 8,
        'SWJ' => 9,
        'WKJ' => 10,
        'RSJ' => 11,
        'TYJRSWJ' => 12,
        'YJGLJ' => 13,
        'ZYGHJ' => 14,
        'SJJ' => 15,
        'TYJ' => 16,
        'ZJJ' => 17,
        'JTJ' => 18,
        'SHUIWJ' => 19,
        'WJW' => 20,
        'STHJJ' => 21,
        'MZJ' => 22,
        'RHNYSZH' => 23,
        'SFJ' => 24,
        'GXJ' => 25,
        'CZJ' => 26,
        'SLJ' => 27,
        'NYNCJ' => 28,
        'TJJ' => 29,
        'KJJ' => 30,
        'ZJFY' => 31,
        'JCY' => 32,
        'MZJ' => 33,
        'YBJ' => 34,
        'RFB' => 35,
        'JRJ' => 36,
        'FPB' => 37,
        'XFJ' => 38,
        'CGJ' => 39,
        'LYJ' => 40,
        'ZYYJ' => 41,
        'NYHG' => 42,
        'GSL' => 43,
        'FGZX' => 44,
        'ZYJYZX' => 45,
    );
}
