<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const IDENTIFY = array(
        IUserGroup::ID['NULL'] => 'NULL',
        IUserGroup::ID['FGW'] => 'FGW',
        IUserGroup::ID['DSJJ'] => 'DSJJ',
        IUserGroup::ID['SCJGJ'] => 'SCJGJ',
        IUserGroup::ID['ZFW'] => 'ZFW',
        IUserGroup::ID['ZZB'] => 'ZZB',
        IUserGroup::ID['XCB'] => 'XCB',
        IUserGroup::ID['GAJ'] => 'GAJ',
        IUserGroup::ID['JYJ'] => 'JYJ',
        IUserGroup::ID['SWJ'] => 'SWJ',
        IUserGroup::ID['WKJ'] => 'WKJ',
        IUserGroup::ID['RSJ'] => 'RSJ',
        IUserGroup::ID['TYJRSWJ'] => 'TYJRSWJ',
        IUserGroup::ID['YJGLJ'] => 'YJGLJ',
        IUserGroup::ID['ZYGHJ'] => 'ZYGHJ',
        IUserGroup::ID['SJJ'] => 'SJJ',
        IUserGroup::ID['TYJ'] => 'TYJ',
        IUserGroup::ID['ZJJ'] => 'ZJJ',
        IUserGroup::ID['JTJ'] => 'JTJ',
        IUserGroup::ID['SHUIWJ'] => 'SHUIWJ',
        IUserGroup::ID['WJW'] => 'WJW',
        IUserGroup::ID['STHJJ'] => 'STHJJ',
        IUserGroup::ID['MZJ'] => 'MZJ',
        IUserGroup::ID['RHNYSZH'] => 'RHNYSZH',
        IUserGroup::ID['SFJ'] => 'SFJ',
        IUserGroup::ID['GXJ'] => 'GXJ',
        IUserGroup::ID['CZJ'] => 'CZJ',
        IUserGroup::ID['SLJ'] => 'SLJ',
        IUserGroup::ID['NYNCJ'] => 'NYNCJ',
        IUserGroup::ID['TJJ'] => 'TJJ',
        IUserGroup::ID['KJJ'] => 'KJJ',
        IUserGroup::ID['ZJFY'] => 'ZJFY',
        IUserGroup::ID['JCY'] => 'JCY',
        IUserGroup::ID['MZZJSWJ'] => 'MZZJSWJ',
        IUserGroup::ID['YBJ'] => 'YBJ',
        IUserGroup::ID['RFB'] => 'RFB',
        IUserGroup::ID['JRJ'] => 'JRJ',
        IUserGroup::ID['FPB'] => 'FPB',
        IUserGroup::ID['XFJ'] => 'XFJ',
        IUserGroup::ID['CGJ'] => 'CGJ',
        IUserGroup::ID['LYJ'] => 'LYJ',
        IUserGroup::ID['ZYYJ'] => 'ZYYJ',
        IUserGroup::ID['NYHG'] => 'NYHG',
        IUserGroup::ID['GSL'] => 'GSL',
        IUserGroup::ID['FGZX'] => 'FGZX',
        IUserGroup::ID['ZYJYZX'] => 'ZYJYZX',
    );
}
